# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Gradle Package

# on:
#   release:
#     types: [created]

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        SLATEKIT_PROJECT_MODE: binary
        SLATEKIT_INSTALL_ACTOR: ${{ secrets.SLATEKIT_INSTALL_ACTOR }}
        SLATEKIT_INSTALL_TOKEN: ${{ secrets.SLATEKIT_INSTALL_TOKEN }}
        SLATEKIT_BINTRAY_ACTOR: ${{ secrets.SLATEKIT_BINTRAY_ACTOR }}
        SLATEKIT_BINTRAY_TOKEN: ${{ secrets.SLATEKIT_BINTRAY_TOKEN }}
        SLATEKIT_PUBLISH_ACTOR: ${{ github.actor }}
        SLATEKIT_PUBLISH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    # Slate Kit-Result
    - name: Build SlateKit.Result with Gradle
      working-directory: src/lib/kotlin/slatekit-result
      run: gradle clean build bintrayUpload
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    # Slate Kit-Actors
    - name: Build SlateKit.Result with Gradle
      working-directory: src/lib/kotlin/slatekit-actors
      run: gradle clean build bintrayUpload
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    # Slate Kit-Common
    - name: Build SlateKit.Result with Gradle
      working-directory: src/lib/kotlin/slatekit-common
      run: gradle clean build bintrayUpload
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    # Slate Kit-Context
    - name: Build SlateKit.Result with Gradle
      working-directory: src/lib/kotlin/slatekit-context
      run: gradle clean build bintrayUpload
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

